<#
.SYNOPSIS
    PowerShell SNMP Printer Monitoring and Reporting Script / PsSPM (ROV-MOAT)

.LICENSE
    Distributed under the MIT License. See the accompanying LICENSE file or https://github.com/ROV-MOAT/PsSPM/blob/main/LICENSE
    
.DESCRIPTION
    Mail function

    Usage:
        Send-UniversalMail -MailFrom "example@example.com" -MailTo "example@example.com" `
                -Body $MailHtmlBody `
                -IsBodyHtml $true `
                -Username "your-username" `
                -Password "your_password" `
                -SmtpServer "smtp.office365.com" `
                -SmtpPort 587 `
                -EnableSsl $true `
                -SslProtocol "Tls12"

        Send-UniversalMail -MailFrom "example@example.com" -MailTo "example@example.com" `
                -UseDefaultCredentials `
                -SmtpServer "smtp.gmail.com" `
                -SmtpPort 465 `
                -EnableSsl $true `
                -SslProtocol "Tls13"

        Send-UniversalMail -MailFrom "example@example.com" -MailTo "example@example.com" `
                -UseDefaultCredentials `
                -SmtpServer "smtp.example.com" `
                -SmtpPort 25 `
                -EnableSsl $false
#>
function Send-UniversalMail {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$MailFrom,
        [Parameter(Mandatory = $true)]
        [string[]]$MailTo,
        [string]$Subject = "PsSPM Report",
        [string]$Body = "This message was automatically generated by PsSPM.",
        [bool]$IsBodyHtml = $false,
        [string[]]$Attachments,
        [string[]]$CC,
        [string[]]$BCC,
        [string]$SmtpServer,
        [int]$SmtpPort = 587,
        [bool]$EnableSsl = $true,
        [switch]$UseDefaultCredentials,
        [string]$Username,
        [string]$Password,
        [string]$Domain,

        [ValidateSet("None", "Tls", "Tls11", "Tls12")]
        [string]$SslProtocol = "Tls12",

        [int]$SmtpTimeoutMs = 30000
    )

    # Force TLS 1.2 globally (best practice for SmtpClient)
    switch ($SslProtocol) {
        "Tls12" { [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12 }
        "Tls11" { [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls11 }
        "Tls"   { [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls }
        "None"  { [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::SystemDefault }
    }

    $mail = $null
    $smtp = $null
    $attachmentsList = @()

    try {
        Write-Log "Preparing email message..."

        # Create message
        $mail = [System.Net.Mail.MailMessage]::new()
        $mail.From = [System.Net.Mail.MailAddress]::new($MailFrom)

        foreach ($r in $MailTo) { $mail.To.Add($r) }
        foreach ($r in $CC)   { $mail.CC.Add($r) }
        foreach ($r in $BCC)  { $mail.Bcc.Add($r) }

        $mail.Subject = $Subject
        $mail.Body = $Body
        $mail.IsBodyHtml = $IsBodyHtml

        # Attachments
        if ($Attachments) {
            foreach ($path in $Attachments) {
                if (Test-Path $path -PathType Leaf) {
                    $att = [System.Net.Mail.Attachment]::new($path)
                    $mail.Attachments.Add($att)
                    $attachmentsList += $att
                    Write-Log "Attachment added: $path"
                }
                else { Write-Log "Attachment not found: $path" -Level "WARNING" }
            }
        }

        # SMTP client
        $smtp = [System.Net.Mail.SmtpClient]::new($SmtpServer, $SmtpPort)
        $smtp.Timeout = $SmtpTimeoutMs
        $smtp.EnableSsl = $EnableSsl

        # Authentication
        if ($UseDefaultCredentials) {
            $smtp.UseDefaultCredentials = $true
            Write-Log "Using default credentials"
        }
        else {
            if (-not $Username -or -not $Password) { throw "Username and Password must be provided unless UseDefaultCredentials is set" }

            $secure = ConvertTo-SecureString $Password -AsPlainText -Force

            if ($Domain) {
                $cred = New-Object System.Net.NetworkCredential($Username, $secure, $Domain)
                Write-Log "Authenticating with domain: $Domain"
            }
            else {
                $cred = New-Object System.Net.NetworkCredential($Username, $secure)
                Write-Log "Authenticating as: $Username"
            }

            $smtp.UseDefaultCredentials = $false
            $smtp.Credentials = $cred
        }

        Write-Log "Sending email via $SmtpServer : $SmtpPort ..."
        $smtp.Send($mail)

        Write-Log "Email sent successfully!"
    }
    catch {
        Write-Log "Error sending email: $($_.Exception.Message)" -Level "ERROR"
        if ($_.Exception.InnerException) { Write-Log "Internal error: $($_.Exception.InnerException.Message)" -Level "ERROR" }
    }
    finally {
        foreach ($att in $attachmentsList) { $att.Dispose() }
        if ($mail) { $mail.Dispose() }
        if ($smtp) { $smtp.Dispose() }
    }
}