<#
.SYNOPSIS
    PowerShell SNMP Printer Monitoring and Reporting Script / PsSPM (ROV-MOAT)

.LICENSE
    Distributed under the MIT License. See the accompanying LICENSE file or https://github.com/ROV-MOAT/PsSPM/blob/main/LICENSE

.DESCRIPTION
    HTML Body and Mail
#>

#region HTML Template
$Header = @"
<style>
    body { font-family: 'Trebuchet MS', sans-serif; margin: 20px; }
    table {
        border-collapse: collapse;
        border: 1px solid black;
        font-size: 90%;
        width: 100%;
        margin-bottom: 20px;
    }
    th, td {
        border: 2px solid #ddd;
        padding: 5px;
        text-align: center;
        font-weight: normal;
        font-size: 15px;
    }
    th {
        font-size: 17px;
        background-color: #6d8196;
        color: white;
        position: sticky;
        top: 0;
    }
    tr:hover { background-color: #f0f0f0; }
    li { margin-top: 5px; margin-bottom: 5px; }
    .online { color: green; }
    .offline { color: red; }
    .error { color: orange; }

    .toner-high { color: green; font-weight: bold; transition: all 0.3s ease; }
    .toner-medium { color: orange; font-weight: bold; transition: all 0.3s ease; }
    .toner-low { color: red; font-weight: bold; transition: all 0.3s ease; }

    a.printer-link { text-decoration: none; color: #0066cc; }
    a.show-link {
        display: inline-block;
        text-decoration: none;
        color: #0066cc;
        animation: show-link ease-in-out 1s infinite alternate;
    }
    @keyframes show-link {
        0% {
            transform: rotate(0deg);
        }
        25% {
            transform: rotate(5deg);
        }
        75% {
            transform: rotate(-5deg);
        }
        100% {
            transform: rotate(0deg);
        }
    }

    .tooltip { position: relative; display: inline-block; }

    /* Tooltip text */
    .tooltip .tooltiptext {
        list-style-position: inside;
        list-style-type: disclosure-closed;
        visibility: hidden;
        max-width: 400px;
        width: max-content; /* Allows the tooltip to size based on content up to max-width */
        white-space: normal; /* Ensures text wraps within the tooltip */
        word-wrap: break-word; /* Prevents long words from overflowing */
        background-color: #6d8196;
        color: #ffffff;
        text-align: Left;
        padding: 5px 5px 7px 5px;
        margin: 0;
        border-radius: 5px;
        opacity: 0;
        transition: visibility 0.3s ease, opacity 0.3s ease, background-color 0.3s ease;
 
        /* Position the tooltip text */
        position: absolute;
        z-index: 1000;
        right: 35px;
        top: 20px;
    }

    /* Show the tooltip text when you mouse over the tooltip container */
    .tooltip:hover .tooltiptext { visibility: visible; opacity: 1; }
    .tooltiptext:hover { background-color: #000000; }

    .container { border-radius: 3px; padding: 5px; margin: 0; text-align: center; transition: all 0.3s ease; }
    .container:hover { background-color: #000000; background-size: cover; }
    .container:hover .toner-high,
    .container:hover .toner-medium,
    .container:hover .toner-low {
        color: #ffffff;
    }
</style>
<span><font color="black">This page was automatically generated by PowerShell SNMP printer monitoring (<a style='text-decoration: none; color: #000000ff;' href='https://github.com/ROV-MOAT/PsSPM' target='_blank'>PsSPM</a>).</font></span>
<p></p>
"@

$MailHtmlBody = @"
<span><font color="black">This message was automatically generated by PowerShell SNMP printer monitoring (PsSPM).</font></span>
<p>Date: $(Get-Date)</p>
"@
#endregion